version: "3"

env:
  APP_DB_URL: postgresql://member:welcome@localhost:5432/member?sslmode=disable

dotenv:
  - .env

tasks:
  container-up:
    cmds:
      - docker-compose up -d
  container-down:
    cmds:
      - docker-compose down --remove-orphans --volumes
  test:
    cmds:
      - go test -v -cover ./...
  pkl-gen:
    cmds:
      - pkl-gen-go configs/Application.pkl
  proto-gen:
    cmds:
      - |
        protoc \
        --proto_path=pkg/proto \
        --go_out=pkg/contract \
        --go_opt=paths=source_relative \
        --go-grpc_out=pkg/contract \
        --go-grpc_opt=paths=source_relative \
        health.proto member.proto
